name: Export Secrets

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload secret artifact
        uses: actions/upload-artifact@v4
        with:
          name: shared-secret
          path: secrets.txt